### ISSUE TITLE
[GLCC] GitLink Code Camp

### ISSUE THREAD

**Issue by FengShang** [FeatureProbe/FeatureProbe#1]
The issue is about the first GitLink Code Camp activity.
Related link: https://mp.weixin.qq.com/s/upVI-2TQ0ezQGpzhDiF3Pg

## Requirement

We need a server-side python SDK, which can work as other FeatureProbe server side SDKs, take Java SDK for example.

You need to be familiar with python, have knowledge of network and multi-thread programming in python.

## Expectation

The python SDK should work as Java SDK, including Targeting calculation and metrics report, and should pass all the acceptance tests including performance test.

## Contact

@dengfeige   
email: dengfeige@featureprobe.com

**Comment by HeZean** [comment]
## GLCC Midterm Progress Report

**Topic: Implementing a server-side SDK of Python**

Related PRs:
- https://github.com/FeatureProbe/server-sdk-python/pull/2
- https://github.com/FeatureProbe/server-sdk-python/pull/1
- https://github.com/FeatureProbe/server-sdk-python/pull/3

There are also some PRs that are not under the topic, but may be relevant:
- https://github.com/FeatureProbe/feature-probe-api/pull/23
- https://github.com/FeatureProbe/feature-probe-ui/pull/8
- https://github.com/FeatureProbe/feature-probe-ui/pull/7
- https://github.com/FeatureProbe/server-sdk-java/pull/9
- https://github.com/FeatureProbe/server-sdk-java/pull/7
