### ISSUE TITLE
Is there any roadmap ?

### ISSUE THREAD

**Issue by xiejiashuai** [FeatureProbe/FeatureProbe#14]
![image](https://user-images.githubusercontent.com/20101707/202650497-82b3857c-84f2-48e7-a028-59f96642a835.png)
官方能不能也给一个类似Sentinel这样的ROADMAP，这里面规划了开源版本会支持的功能以及明确的时间点，通过这个图我们能够非常清晰的看到咱们的迭代计划。

**Comment by FengShang** [comment]
Thanks for ask. We will update our roadmap to Project soon.

**Comment by FengShang** [comment]
You can find the roadmap here: https://github.com/orgs/FeatureProbe/projects/2/views/4
