### ISSUE TITLE
Three services are sometimes too heavy

### ISSUE THREAD

**Issue by Zhaoyu620** [FeatureProbe/FeatureProbe#189]
For scenarios where there are not many services in the cluster, it is too heavy to deploy three services as function switches. It is recommended to provide a solution to simplify the deployment of the number of services.

**Comment by SSebo** [comment]
@Zhaoyu620 How about we deploy server and api in the same instance?

**Comment by Zhaoyu620** [comment]
> @Zhaoyu620 How about we deploy server and api in the same instance?

that is great

**Comment by Zhaoyu620** [comment]
@SSebo That is great

**Comment by gangb-tech** [comment]
We provide an All-in-One deployment method, please refer to: [All-In-One Deploy Guide](https://docs.featureprobe.io/en/how-to/deploy/deployment-docker-all-in-one)
