### ISSUE TITLE
Request: SDK for flutter

### ISSUE THREAD

**Issue by MeowTechOpenSource** [FeatureProbe/FeatureProbe#193]
Flutter is being user for cross platform, and there is no native SDK or SDK/API documentation for how the SDKs are built. Hope there will be a Flutter client. Thanks!

**Comment by SSebo** [comment]
@MeowTechOpenSource Thanks for your attention. Flutter SDK is on our plan.

**Comment by SSebo** [comment]
@MeowTechOpenSource https://github.com/FeatureProbe/client-sdk-flutter we provide a beta version of flutter sdk :)
