### ISSUE TITLE
docker compose up failed

### ISSUE THREAD

**Issue by cmonkey** [FeatureProbe/FeatureProbe#2]
![image](https://user-images.githubusercontent.com/664050/172088709-22d8ebe0-1724-4173-b910-790eada945dd.png)

**Comment by dengfeige** [comment]
Thanks for your question.
Please provide more detailed information. For example, what operating system is used? What is the docker version?

**Comment by dengfeige** [comment]
You can try `docker compose pull` to update the latest image.

**Comment by cmonkey** [comment]
> Thanks for your question. Please provide more detailed information. For example, what operating system is used? What is the docker version?

ArchLinux, kernel version 5.18.1-arch-1
docker version 20.10.16

**Comment by cmonkey** [comment]
> You can try `docker compose pull` to update the latest image.

thank, pull success after then launch

**Comment by dongliutony** [comment]
Thanks for confirming the issue was resolved. Closing it.
