### ISSUE TITLE
[GLCC] GitLink Code Camp, Support C# Server SDK

### ISSUE THREAD

**Issue by FengShang** [FeatureProbe/FeatureProbe#26]
The issue is about the GitLink Code Camp activity.

## Requirement

We need a server-side C# SDK, which can work as other FeatureProbe server side SDKs, take Java SDK for example.

You need to be familiar with C#, have knowledge of network and multi-thread programming in C#.

## Expectation

The C# SDK should work as Java SDK, including Targeting calculation and metrics report, and should pass all the acceptance tests including performance test.

## Contact

@dengfeige   
email: dengfeige@featureprobe.com

**Comment by DDreame** [comment]
I have interesting in this issue， and I will send a proposal in the next week.
