### ISSUE TITLE
[Feature request] Consider for Add LDAP Support  

### ISSUE THREAD

**Issue by csh0101** [FeatureProbe/FeatureProbe#293]
Do you consider ADD LDAP Support for FeatureProbe 
I think we can map the LDAP user/email 2 inner member.
the logic is make sense.
just add a SpringSecurity Provider  for api.
and add a icon for ldap login for ui..

the details can discusstion.
the key point is 
Do you think is need to Support this?

**Comment by csh0101** [comment]
if you received pr, i can do this by myself..

**Comment by csh0101** [comment]
just for open source !!

**Comment by FengShang** [comment]
> Do you consider ADD LDAP Support for FeatureProbe I think we can map the LDAP user/email 2 inner member. the logic is make sense. just add a SpringSecurity Provider for api. and add a icon for ldap login for ui..
> 
> the details can discusstion. the key point is Do you think is need to Support this?

Yes, we think this make sense, it's also helpful for other users. Please feel free to add this feature, we accept PRs. Thanks!

**Comment by csh0101** [comment]
I have a Problem for the Code. Just I want to Know the mean of Organization struct.
I find the the instance docker-compose started , the X-OrganizeID is 1 , and the Name is Organization Name is Default Organizetion.
so My problem is, these thing Organization,(Name ID) is built-in and default set is exec by migrate/sql.
In this Context,My Idea about implementing the LDAP Login is following step:
1. /api/ldap/login （if have, the front support）
2. Customized  Filter Provider in Sprint Security 
3. if the authenticate by ldap server is true, there will create a the same account/password in member table in FeatProbe.Because of the `OrganizationMemberlModel` is get from the token (if I right understand the TenantConext Logic), but the account is not created at the now.so this like a problem `chicken before egg or egg before chicken`.
i find a tricky solutions to resolve it. just hardcode set the OrganizationMemberModel , like this `Default Organization`, 1 ,Writter and anything else. 

the basic mind. please review this and give me back suggestions. Thanks!

**Comment by gangb-tech** [comment]
To isolate data from different tenants, we use the 'organization_id' field. Here are some suggestions to keep in mind:

**The following suggestions are for reference.**

- The open-source version lacks tenant management functionality, so there's only one tenant with the Admin account and an organization_id of 1.
- The 'organization_member' table should be used to bind the relationship between tenants and users.
- When implementing LDAP, ensure that all subdirectories are under the same tenant. For the open-source version, this means they should be under the tenant with organization_id 1.

We hope this explanation helps you. Have a great day!

**Comment by gangb-tech** [comment]
> I have a Problem for the Code. Just I want to Know the mean of Organization struct. I find the the instance docker-compose started , the X-OrganizeID is 1 , and the Name is Organization Name is Default Organizetion. so My problem is, these thing Organization,(Name ID) is built-in and default set is exec by migrate/sql. In this Context,My Idea about implementing the LDAP Login is following step:
> 
> 1. /api/ldap/login （if have, the front support）
> 2. Customized  Filter Provider in Sprint Security
> 3. if the authenticate by ldap server is true, there will create a the same account/password in member table in FeatProbe.Because of the `OrganizationMemberlModel` is get from the token (if I right understand the TenantConext Logic), but the account is not created at the now.so this like a problem `chicken before egg or egg before chicken`.
>    i find a tricky solutions to resolve it. just hardcode set the OrganizationMemberModel , like this `Default Organization`, 1 ,Writter and anything else.
> 
> the basic mind. please review this and give me back suggestions. Thanks!

**To isolate data from different tenants, we use the 'organization_id' field. Here are some suggestions to keep in mind:**

**The following suggestions are for reference.**

- The open-source version lacks tenant management functionality, so there's only one tenant with the Admin account and an organization_id of 1.
- The 'organization_member' table should be used to bind the relationship between tenants and users.
- When implementing LDAP, ensure that all subdirectories are under the same tenant. For the open-source version, this means they should be under the tenant with organization_id 1.

We hope this explanation helps you. Have a great day!

**Comment by csh0101** [comment]
> > I have a Problem for the Code. Just I want to Know the mean of Organization struct. I find the the instance docker-compose started , the X-OrganizeID is 1 , and the Name is Organization Name is Default Organizetion. so My problem is, these thing Organization,(Name ID) is built-in and default set is exec by migrate/sql. In this Context,My Idea about implementing the LDAP Login is following step:
> > 
> > 1. /api/ldap/login （if have, the front support）
> > 2. Customized  Filter Provider in Sprint Security
> > 3. if the authenticate by ldap server is true, there will create a the same account/password in member table in FeatProbe.Because of the `OrganizationMemberlModel` is get from the token (if I right understand the TenantConext Logic), but the account is not created at the now.so this like a problem `chicken before egg or egg before chicken`.
> >    i find a tricky solutions to resolve it. just hardcode set the OrganizationMemberModel , like this `Default Organization`, 1 ,Writter and anything else.
> > 
> > the basic mind. please review this and give me back suggestions. Thanks!
> 
> **To isolate data from different tenants, we use the 'organization_id' field.**
> 
> **The following suggestions are for reference.**
> 
> * The open-source version lacks tenant management functionality, so there's only one tenant with the Admin account and an organization_id of 1.
> * The 'organization_member' table should be used to bind the relationship between tenants and users.
> * When implementing LDAP, ensure that all subdirectories are under the same tenant. For the open-source version, this means they should be under the tenant with organization_id 1.
> 
> We hope this explanation helps you. Have a great day!

Thanks your suggestions very Much. And I will plan to contribute my code for this project! Maybe its will need some time,maybe a week or half a month.
I'm a Gopher, and write java in university, so just to fix the code style pattern,and pass the validation of the maven plugins on situation OSS ,it's a struggle for me. and maybe i will request for help to make a sure the quality of the code.

**Comment by csh0101** [comment]
```java
@Component(value = "ldap")
@AllArgsConstructor
@Qualifier("ldap")
@Slf4j
@Primary
public class LDAPAccountValidator implements AccountValidator{

    private MemberService memberService;

    private OperationLogService operationLogService;

    private LdapTemplate ldapTemplate;

    @Override
    public Authentication authenticate(Authentication authentication) {
        UserPasswordAuthenticationToken token = (UserPasswordAuthenticationToken) authentication;
        try {
            ldapTemplate.authenticate(query().where("uid").is(token.getAccount()),token.getPassword());
        }catch (RuntimeException e) {
            log.warn(e.toString());
            return null;
        }

        Optional<Member> members =  memberService.findByAccount(token.getAccount());

        if (!members.isPresent()) {
            MemberCreateRequest memberCreateRequest = new MemberCreateRequest();
            memberCreateRequest.setPassword(token.getPassword());
            memberCreateRequest.setRole(OrganizationRoleEnum.WRITER);
            ArrayList<String> accounts = new ArrayList<>();
            accounts.add(token.getAccount());
            memberCreateRequest.setAccounts(accounts);
            TenantContext.setCurrentTenant("1");
            TenantContext.setCurrentOrganization(
                    new OrganizationMemberModel(1L,"Default Organize",OrganizationRoleEnum.WRITER)
            );
                List<MemberResponse> memberResponses = memberService.create(memberCreateRequest);
                if (Objects.isNull(memberResponses) || memberResponses.isEmpty() ) {
                    return null;
                }
                String registerAccounts = memberResponses.stream()
                        .map(MemberResponse::getAccount)
                        .collect(Collectors.joining(","));
                OperationLog log = new OperationLog(OperationType.LOGIN.name()+"_"+token.getSource(),registerAccounts);
                operationLogService.save(log);
        }
        if(StringUtils.isNotBlank(token.getAccount()) && StringUtils.isNotBlank(token.getPassword())) {
            Optional<Member> member = memberService.findByAccount(token.getAccount());
            OperationLog log = new OperationLog(OperationType.LOGIN.name() + "_" + token.getSource(),
                        token.getAccount());
            if (!member.isPresent() || isAccessTokenNumber(member)) {
                return null;
            }
            boolean passwordMatched = new BCryptPasswordEncoder().matches(token.getPassword(),
                    member.get().getPassword());
            if (passwordMatched && MemberStatusEnum.ACTIVE.name().equals(member.get().getStatus().name())) {
                memberService.updateVisitedTime(token.getAccount());
                operationLogService.save(log);
                return new UserPasswordAuthenticationToken(AuthenticatedMember.create(member.get()),
                        Collections.emptyList());
            }
        }
        return null;

    }

    private boolean isAccessTokenNumber(Optional<Member> member) {
        return StringUtils.equalsIgnoreCase(member.get().getSource(), MemberSourceEnum.ACCESS_TOKEN.name());
    }
} 
```
I meet a problem. In this code after create meber, but the findByAccount only can get a meber have only two field password and account, anything else is empty (null) . I want to know this is why . I try commit transaction after create but it's no good. Maybe this is a jpa problem? but I don't know how to slove it.

**Comment by csh0101** [comment]
please help me @FengShang

**Comment by gangb-tech** [comment]
> > > I have a Problem for the Code. Just I want to Know the mean of Organization struct. I find the the instance docker-compose started , the X-OrganizeID is 1 , and the Name is Organization Name is Default Organizetion. so My problem is, these thing Organization,(Name ID) is built-in and default set is exec by migrate/sql. In this Context,My Idea about implementing the LDAP Login is following step:
> > > 
> > > 1. /api/ldap/login （if have, the front support）
> > > 2. Customized  Filter Provider in Sprint Security
> > > 3. if the authenticate by ldap server is true, there will create a the same account/password in member table in FeatProbe.Because of the `OrganizationMemberlModel` is get from the token (if I right understand the TenantConext Logic), but the account is not created at the now.so this like a problem `chicken before egg or egg before chicken`.
> > >    i find a tricky solutions to resolve it. just hardcode set the OrganizationMemberModel , like this `Default Organization`, 1 ,Writter and anything else.
> > > 
> > > the basic mind. please review this and give me back suggestions. Thanks!
> > 
> > 
> > **To isolate data from different tenants, we use the 'organization_id' field.**
> > **The following suggestions are for reference.**
> > 
> > * The open-source version lacks tenant management functionality, so there's only one tenant with the Admin account and an organization_id of 1.
> > * The 'organization_member' table should be used to bind the relationship between tenants and users.
> > * When implementing LDAP, ensure that all subdirectories are under the same tenant. For the open-source version, this means they should be under the tenant with organization_id 1.
> > 
> > We hope this explanation helps you. Have a great day!
> 
> Thanks your suggestions very Much. And I will plan to contribute my code for this project! Maybe its will need some time,maybe a week or half a month. I'm a Gopher, and write java in university, so just to fix the code style pattern,and pass the validation of the maven plugins on situation OSS ,it's a struggle for me. and maybe i will request for help to make a sure the quality of the code.

That's great to hear! We're glad to offer our assistance. If you have any questions or need further support, please feel free to let us know. We're here to help!

**Comment by csh0101** [comment]
@gangb-tech  please review my code. And I fix the code after you repackage. a big change!!

**Comment by gangb-tech** [comment]
@csh0101  It would be even better if you could contribute a document on how to access LDAP.

**Comment by csh0101** [comment]
Yes,I will do this

**Comment by csh0101** [comment]
> @csh0101 It would be even better if you could contribute a document on how to access LDAP.
> 
> Chinese document path："FeatureProbe/docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/reference"
> 
> English document path："FeatureProbe/docs/docs/reference"

Yes I will do this in the  evening today.
