### ISSUE TITLE
Does the SDK support Electron?

### ISSUE THREAD

**Issue by wbcyclist** [FeatureProbe/FeatureProbe#304]

**Comment by gangb-tech** [comment]
Currently, we do not have any immediate plans for developing an Electron SDK. However, you can leverage the JS SDK as a suitable alternative. If you happen to be interested in contributing to the community by developing an Electron SDK, your efforts would be highly appreciated and welcomed.

**Comment by wbcyclist** [comment]
Ok, thanks for your reply
