### ISSUE TITLE
[Code Confused] I m confused about the code in FeatProbeServer 

### ISSUE THREAD

**Issue by csh0101** [FeatureProbe/FeatureProbe#308]
Because of I m intersted in this project. And I had learned about the Rust. So I read the code.
But I m  confused about this code snippet.
``` Rust
       let config = FPConfig {
            server_sdk_key: server_sdk_key.to_owned(),
            remote_url: Url::parse("http://nouse.com").unwrap(),
            toggles_url: Some(self.server_config.toggles_url.clone()),
            refresh_interval: self.server_config.refresh_interval,
            http_client: Some(self.http_client.clone()),
            ..Default::default()
        };
````
in repo.rs..

so what do this line do ?  ** remote_url: Url::parse("http://nouse.com").unwrap(),**

I find the nouse.com is a domain no body  use

**Comment by gangb-tech** [comment]
> Because of I m intersted in this project. And I had learned about the Rust. So I read the code. But I m confused about this code snippet.
> 
> ```rust
>        let config = FPConfig {
>             server_sdk_key: server_sdk_key.to_owned(),
>             remote_url: Url::parse("http://nouse.com").unwrap(),
>             toggles_url: Some(self.server_config.toggles_url.clone()),
>             refresh_interval: self.server_config.refresh_interval,
>             http_client: Some(self.http_client.clone()),
>             ..Default::default()
>         };
> ```
> 
> in repo.rs..
> 
> so what do this line do ? ** remote_url: Url::parse("[http://nouse.com").unwrap(](http://nouse.com%22).unwrap()),**
> 
> I find the nouse.com is a domain no body use

In most cases, when deploying according to the official configuration, you only need to set the 'remote_url' parameter. The relevant interfaces will use the default path and concatenate it with the specified URL.

However, if users have set up their own gateway to forward interface addresses, they can configure their own complete interface address using the 'toggles_url' parameter.

**Comment by SSebo** [comment]
@csh0101 `nouse.com` means no one used, this is just for test.

**Comment by csh0101** [comment]
tks
