### ISSUE TITLE
Allow special characters in password field on the login page when LDAP is enabled

### ISSUE THREAD

**Issue by aliaksei-audonin** [FeatureProbe/FeatureProbe#316]
**Describe the bug**
With enabled LDAP I can't log in because my password contains a special character (#).

**To Reproduce**
1. Go to login page.
2. Type username an password. Password contains a special character.
4. See error "invalid password Password can only contain letters, numbers, '.', '_' or '-'."

**Expected behavior**
Log in to the system with password that contains special characters when LDAP is enabled.

**Desktop:**
 - OS: Debian GNU/Linux
 - Browser : chrome
 - Version: 2.6.1

**Comment by aliaksei-audonin** [comment]
Proposed changes: https://github.com/FeatureProbe/FeatureProbe/pull/321

**Comment by FengShang** [comment]
@aliaksei-audonin  thanks for the PR, it has been merged. 

By the way, are you using this project in your daily work?
