### ISSUE TITLE
[Bug] Python 中 fp.User().with_attr('xxx', 0) 不能触发规则： if 数值 xxx = 0

### ISSUE THREAD

**Issue by titer18** [FeatureProbe/FeatureProbe#325]
<img width="1871" alt="image" src="https://github.com/FeatureProbe/FeatureProbe/assets/3861325/90d0cc91-d2b1-4bc5-ae61-f47a65bcfd88">

1. 使用 Python sdk，设置 realtime = 0，获取 auto_type 值
2. 在规则判断中，配置 if 数值 realtime = 0 时，返回 非医美项目
3. 预期返回：非医美项目
4. 实际返回：默认规则

如果配置 1 和 2，能正确识别，不能识别等于0的情况；

疑问：
在规则判断中，如何配置判断布尔值条件？

**Comment by hezean** [comment]
Hi, the user's attribute value should always be `str`, you may check my example with account `test@featureprobe.com` on https://featureprobe.io, toggle `issue 325`.

```python
import featureprobe as fp

if __name__ == '__main__':
    FEATURE_PROBE_SERVER_URL = 'https://featureprobe.io/server'
    config = fp.Config(remote_uri=FEATURE_PROBE_SERVER_URL, sync_mode='polling')

    SDK_KEY = 'server-bbb12b2cdf58c27c43d034d7bdd54ec97e836734'
    with fp.Client(SDK_KEY, config) as client:
        user = fp.User()
        user['realtime'] = '0'

        TOGGLE_KEY = 'issue_325'
        is_open = client.value(TOGGLE_KEY, user, default=False)
        print('feature for this user is: ' + str(is_open))

        is_open_detail = client.value_detail(TOGGLE_KEY, user, default=False)
        print('detail: ' + str(is_open_detail.reason))
        print('rule index: ' + str(is_open_detail.rule_index))
```

![image](https://github.com/FeatureProbe/FeatureProbe/assets/49837965/d71313fe-f4d8-40d1-b51b-6d16317ff969)

**Comment by dengfeige** [comment]
However, it can be improved in the SDK: Convert attribute value in user to `str` before comparison.
