### ISSUE TITLE
文档教程中搭建部署链接缺失404

### ISSUE THREAD

**Issue by slackab** [FeatureProbe/FeatureProbe#331]
**Describe the bug**
文档教程中搭建部署链接缺失404

**To Reproduce**
访问：https://docs.featureprobe.com/zh-CN/ 404

**Comment by dengfeige** [comment]
请访问：https://docs.featureprobe.io/zh-CN/   
如在访问时自动重定向到 docs.featureprobe.com，请清理下浏览器缓存或开 "无痕模式" 浏览。
