### ISSUE TITLE
golangSDK获取开关数据，中文显示为问号

### ISSUE THREAD

**Issue by huanting0016** [FeatureProbe/FeatureProbe#358]
**Is your feature request related to a problem? Please describe.**
在本地部署的featureprobe服务，镜像使用的all in one部署，最新的版本；数据库自设的mysql 8.0。
目前在网页上配置的内容如下
![image](https://github.com/FeatureProbe/FeatureProbe/assets/53136616/5f5de2de-fcfa-4749-8fed-6bf27c6ad07f)
其中有设置中文，但是通过golang的sdk获取后，显示为???
![image](https://github.com/FeatureProbe/FeatureProbe/assets/53136616/ac27189c-5b4d-418f-9cfb-44b3eb41c27e)

猜想是不是数据库的字符集有区别，或者是mysql和mariadb有区别（因为按照部署环境建议进行设置的）
![image](https://github.com/FeatureProbe/FeatureProbe/assets/53136616/e77d88b9-2d25-4bc1-9a4d-fd26b3cd6884)

想问一下有没有解决的办法

**Comment by gangb-tech** [comment]
可以通过debug查看，确认下server端给到数据是否为乱码

**Comment by huanting0016** [comment]
请问 all in one使用的 featureprobe/featureprobe  镜像是否是最新代码打包的，更换了数据库还是会报相同的异常
