### ISSUE TITLE
Request：关于PG的支持特性相关文档丢失

### ISSUE THREAD

**Issue by 1inuxboy** [FeatureProbe/FeatureProbe#370]
你好，期待答复。

文档目前有大量的无效网页，根据搜索有如下结果，
![image](https://github.com/FeatureProbe/FeatureProbe/assets/121946909/e968b35c-ab5b-4f9d-a884-8c150de04bb4)

页面跳转后发现缺少相关的一个内容，请问目前有相关的文档支持吗？
- 跳转相关的url为：https://docs.featureprobe.com/reference/support-postgresql/

如果没有相关文档，望答复PG部署的相关配置及对PG支持情况。谢谢

**Comment by FengShang** [comment]
看起来这是你安装的某个大模型插件的幻觉，我们并没有提供类似网页url。 项目本身是PG数据库兼容的，虽然默认配置是mysql。

**Comment by hezean** [comment]
> 看起来这是你安装的某个大模型插件的幻觉

@FengShang seems that it could be attributed to not properly configuring the docs site's built in algolia search (one possible reason is that the docs site's domain has been changed), maybe an update of algolia config in their dashboard can fix it

<img width="1512" alt="Screenshot 2024-01-03 at 03 51 59" src="https://github.com/FeatureProbe/FeatureProbe/assets/49837965/66ed32ae-f7c9-4d25-8b6e-fa58981f0759">

ref: https://docusaurus.io/docs/search

<img width="890" alt="Screenshot 2024-01-03 at 03 50 54" src="https://github.com/FeatureProbe/FeatureProbe/assets/49837965/1d2a57d0-2db0-4713-a90b-9418246c9d9c">

**Comment by 1inuxboy** [comment]
Thank you for your response. It appears to be an issue with the documentation's search engine.I have now found the relevant configuration for PG support by reviewing the code repository.Much appreciated.

**Comment by frankzhaopeng** [comment]
> 你好，期待答复。
> 
> 文档目前有大量的无效网页，根据搜索有如下结果， ![image](https://private-user-images.githubusercontent.com/121946909/292123899-e968b35c-ab5b-4f9d-a884-8c150de04bb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTExNDQsIm5iZiI6MTcwNDcxMDg0NCwicGF0aCI6Ii8xMjE5NDY5MDkvMjkyMTIzODk5LWU5NjhiMzVjLWFiNWItNGY5ZC1hODg0LThjMTUwZGUwNGJiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxMDQ3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDRhMTFmYWZjOTk5ZjMzYjI4M2Q2NDMyZjE0ZmQ3MTE5ZjE3MDhlOTAxZDAwZWMyZjUxMGU0ZDM3OGQyZjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.85ZoKvbvnkM_rpvRMfCNesByj0_ljINhIZyOlkDGphA)
> 
> 页面跳转后发现缺少相关的一个内容，请问目前有相关的文档支持吗？
> 
> * 跳转相关的url为：https://docs.featureprobe.com/reference/support-postgresql/
> 
> 如果没有相关文档，望答复PG部署的相关配置及对PG支持情况。谢谢

Actually, we did write a reference article for PostgreSQL. However, during the migration process, this article got lost. Thank you for bringing it to our attention, and we will work to restore it as soon as possible.

**Comment by frankzhaopeng** [comment]
Reference here: https://docs.featureprobe.com/zh-CN/reference/support-postgresql

**Comment by 1inuxboy** [comment]
> Reference here: https://docs.featureprobe.com/zh-CN/reference/support-postgresql/

I apperciate you reply,however,when attempting to open the relevant webpage,it encountered a 502 error.
![image](https://github.com/FeatureProbe/FeatureProbe/assets/121946909/4fd6ffda-43f6-4cc4-8bb3-5d18ebca4150)
