### ISSUE TITLE
按照文档流程python sdk无法连接到本地

### ISSUE THREAD

**Issue by joody-6** [FeatureProbe/FeatureProbe#372]
**Describe the bug**
![image](https://github.com/FeatureProbe/FeatureProbe/assets/148608504/2226200e-11f3-4ceb-9193-8d3a17b29ac2)

**To Reproduce**
我在官网创建了一个开关，在本地写了个如上图所示的demo，无法连接

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gangb-tech** [comment]
Join the community and seek assistance by visiting [https://github.com/FeatureProbe/FeatureProbe?tab=readme-ov-file#-community-and-sharing.](https://github.com/FeatureProbe/FeatureProbe?tab=readme-ov-file#-community-and-sharing.%E2%80%9D)

> **Describe the bug** A clear and concise description of what the bug is. ![image](https://private-user-images.githubusercontent.com/148608504/294704500-2226200e-11f3-4ceb-9193-8d3a17b29ac2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzUxNjksIm5iZiI6MTcwNDg3NDg2OSwicGF0aCI6Ii8xNDg2MDg1MDQvMjk0NzA0NTAwLTIyMjYyMDBlLTExZjMtNGNlYi05MTkzLThkM2ExN2IyOWFjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwODIxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGIwNTMxOWFlMGQxN2FiMTRjNmYxYjM1ODQxN2ZiN2M3NmI1OTYxNDBhNTRiMmM0MDI3OGZiMmRjOWU0MDI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UHqF3i5kiIUCjczE89FTakavqRo5I660aFh4j9nVHhk)
> 
> **To Reproduce** Steps to reproduce the behavior: 我在官网创建了一个开关，在本地写了个如上图所示的demo，无法连接
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

Join the community and seek assistance by visiting [https://github.com/FeatureProbe/FeatureProbe?tab=readme-ov-file#-community-and-sharing.](https://github.com/FeatureProbe/FeatureProbe?tab=readme-ov-file#-community-and-sharing.%E2%80%9D)
