### ISSUE TITLE
Bug: 使用 2.7.0 版本时，删除一个成员后，成员列表不可用的问题。

### ISSUE THREAD

**Issue by tinet-wanghao** [FeatureProbe/FeatureProbe#378]
使用 2.7.0 版本时，删除一个成员后，成员列表不可用的问题。MySQL、PostgreSQL都验证了，都有这个问题。

* 页面的错误提示
![image](https://github.com/FeatureProbe/FeatureProbe/assets/62681807/163bbd66-4bc1-4ada-b7f3-a5edd0c5b956)

* API服务的错误日志 
<img width="1506" alt="image" src="https://github.com/FeatureProbe/FeatureProbe/assets/62681807/9f3eb620-7828-4466-93c7-bad232d0b9c5">

**Comment by apgmer** [comment]
![image](https://github.com/FeatureProbe/FeatureProbe/assets/9553342/28619750-8869-47df-ac67-1c3712248058)

backendAPI

同报错

**Comment by Orlando-li** [comment]
fixed by PR [https://github.com/FeatureProbe/FeatureProbe/pull/380](PR url)
