### ISSUE TITLE
featureprobe官网打不开了，没法看文档了

### ISSUE THREAD

**Issue by zhifan917** [FeatureProbe/FeatureProbe#404]
打开报错如下：{"message":"Service not registered, please register service first"}
截图：
![1717407376035](https://github.com/FeatureProbe/FeatureProbe/assets/40556830/3ba0d4b1-651a-46b5-b9f7-3db1f0366ee1)

**Comment by frankzhaopeng** [comment]
业务调整官网已下线，如需查看用户手册等文档，可访问：https://featureprobe.github.io/FeatureProbe/
